Lower calibration thread priority
jrl-umi3218/mc_force_sensor_calibration_controller pull request #4
Opened 2022-10-12 15:48 UTC by arntanguy

The calibration thread inherits the real-time thread's priority. As this is a computationally intensive thread, this causes the controller to freeze while the calibration is being computed, which can take several seconds (or more if it does not converge).

This PR reduces the thread priority to avoid such issues.
This was tested on `hrp2012c`, I will merge when pipeline succeeds.

2022-10-13 00:05 UTC, gergondet requested changes
LGTM except for the Windows compatibility and the error message for failing to set a lower priority

2022-10-13 00:05 UTC, gergondet commented on src/states/RunCalibrationScript.cpp
> +  pthread_setschedparam(th_handle, SCHED_RR, &param);
This should be surrounded with `#ifndef WIN32` (or something better that checks that `std::thread` implementation is pthread based)

2022-10-13 00:05 UTC, gergondet commented on src/states/RunCalibrationScript.cpp
> +  pthread_setschedparam(th_handle, SCHED_RR, &param);
This call might fail if the user doesn't have permissions to set such high priority (but in that case it's likely not running in a real-time system). In any case, we shouldn't ignore the call result and display a message if appropriate

2022-10-13 12:07 UTC, arntanguy commented
I added the check for windows system (I'm not sure how one would ensure that a thread implementation is pthread-based), and added an error message in case it fails.

2022-10-14 01:51 UTC, gergondet approved these changes

2022-10-14 01:51 UTC, merged