Support panda_brace
jrl-umi3218/mc_force_sensor_calibration_controller pull request #7
Opened 2023-04-18 13:51 UTC by arntanguy

This PR adds support for calibration with the `PandaBrace` robot module (panda with a prosthesis attached).

It also fixes the automatic computation of the initial guess:
- On HRP* variants the mass of the link attached to the force sensor is included in its parent
- On more reasonable robot models the mass of the link is in its children

It also fixes an issue when controlling robots in velocity. In that case while running the calibration script we need to ensure that the robot fully stopped moving before running the calibration. This ensures that in case the calibration script blocks due to high computation loads, the robot does not keep on moving uncontrolled.

2023-04-18 14:55 UTC, gergondet requested changes

2023-04-18 14:55 UTC, gergondet commented on README.md
> +      includeparent: true
I think `includeParent` would be better

2023-04-18 14:55 UTC, gergondet commented on etc/ForceSensorCalibration.in.yaml
> +panda_brace_femur:
ideally, instead of doing this we should use the robot's specific configuration feature introduced in https://github.com/jrl-umi3218/mc_rtc/pull/327 and move the configurations out of there

2023-04-19 09:22 UTC, arntanguy commented
I have moved all robots configuration but `jvrc1` into their own configuration file defined in their corresponding robot module.

Merging when pipeline succeeds.

2023-04-19 13:38 UTC, gergondet approved these changes

2023-04-19 14:05 UTC, merged